# Generated by Django 4.0 on 2021-12-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageuser',
            name='user',
        ),
    ]
