# Generated by Django 4.0 on 2021-12-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageUser',
        ),
    ]
